<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Department extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Department_model');
    } 

    /*
     * Listing of department
     */
    function index()
    {
        $data['department'] = $this->Department_model->get_all_department();
        
        $data['_view'] = 'department/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new department
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('department_name','Department Name','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'department_name' => $this->input->post('department_name'),
            );
            
            $department_id = $this->Department_model->add_department($params);
            redirect('department/index');
        }
        else
        {            
            $data['_view'] = 'department/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a department
     */
    function edit($department_id)
    {   
        // check if the department exists before trying to edit it
        $data['department'] = $this->Department_model->get_department($department_id);
        
        if(isset($data['department']['department_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('department_name','Department Name','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'department_name' => $this->input->post('department_name'),
                );

                $this->Department_model->update_department($department_id,$params);            
                redirect('department/index');
            }
            else
            {
                $data['_view'] = 'department/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The department you are trying to edit does not exist.');
    } 

    /*
     * Deleting department
     */
    function remove($department_id)
    {
        $department = $this->Department_model->get_department($department_id);

        // check if the department exists before trying to delete it
        if(isset($department['department_id']))
        {
            $this->Department_model->delete_department($department_id);
            redirect('department/index');
        }
        else
            show_error('The department you are trying to delete does not exist.');
    }
    
}
