<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Participate_team extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Participate_team_model');
        $this->load->library('session');
    } 

    /*
     * Listing of participate_team
     */
    function index()
    {
        $data['participate_team'] = $this->Participate_team_model->get_all_participate_team();
        
        $data['_view'] = 'participate_team/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new participate_team
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('leader_registration_id','Leader Registration Id','required');
		$this->form_validation->set_rules('email_id','Email Id','required');
		$this->form_validation->set_rules('mobile_no','Mobile No','required');
		$this->form_validation->set_rules('department','Department','required');
		$this->form_validation->set_rules('members1_id','Members1 Id','required');
		$this->form_validation->set_rules('sport','Sport','required');
		$this->form_validation->set_rules('members2_id','Members2 Id','required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'leader_registration_id' => $this->input->post('leader_registration_id'),
				'department' => $this->input->post('department'),
				'sport' => $this->input->post('sport'),
				'members1_id' => $this->input->post('members1_id'),
				'members2_id' => $this->input->post('members2_id'),
                'members3_id' => $this->input->post('members3_id'),
                'members4_id' => $this->input->post('members4_id'),
                'members5_id' => $this->input->post('members5_id'),
                'members6_id' => $this->input->post('members6_id'),
                'members7_id' => $this->input->post('members7_id'),
				'email_id' => $this->input->post('email_id'),
				'mobile_no' => $this->input->post('mobile_no'),
            );
            
            $participate_team_id = $this->Participate_team_model->add_participate_team($params);
            redirect('student/index');
        }
        else
        {
			$this->load->model('Student_registartion_model');
			$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();
             $student_id = $this->session->userdata('student_id');
            $data['student_registartion'] = $this->Student_registartion_model->get_student_registartion($student_id);
			$this->load->model('Department_model');
			$data['all_department'] = $this->Department_model->get_all_department();

			$this->load->model('Sport_info_model');
			$data['all_sport_info'] = $this->Sport_info_model->get_all_sport_info();
			$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();
			$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();
            
            /*$data['_view'] = 'participate_team/add'*/;
            $this->load->view('participate_team/add',$data);
        }
    }  

    /*
     * Editing a participate_team
     */
    function edit($team_id)
    {   
        // check if the participate_team exists before trying to edit it
        $data['participate_team'] = $this->Participate_team_model->get_participate_team($team_id);
        
        if(isset($data['participate_team']['team_id']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('leader_registration_id','Leader Registration Id','required');
			$this->form_validation->set_rules('email_id','Email Id','required');
			$this->form_validation->set_rules('mobile_no','Mobile No','required');
			$this->form_validation->set_rules('department','Department','required');
			$this->form_validation->set_rules('members1_id','Members1 Id','required');
			$this->form_validation->set_rules('sport','Sport','required');
			$this->form_validation->set_rules('members2_id','Members2 Id','required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'leader_registration_id' => $this->input->post('leader_registration_id'),
					'department' => $this->input->post('department'),
					'sport' => $this->input->post('sport'),
					'members1_id' => $this->input->post('members1_id'),
					'members2_id' => $this->input->post('members2_id'),
                    'members3_id' => $this->input->post('members3_id'),
                    'members4_id' => $this->input->post('members4_id'),
                    'members5_id' => $this->input->post('members5_id'),
                    'members6_id' => $this->input->post('members6_id'),
                    'members7_id' => $this->input->post('members7_id'),
					'email_id' => $this->input->post('email_id'),
					'mobile_no' => $this->input->post('mobile_no'),
                );

                $this->Participate_team_model->update_participate_team($team_id,$params);            
                redirect('participate_team/index');
            }
            else
            {
				$this->load->model('Student_registartion_model');
				$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();

				$this->load->model('Department_model');
				$data['all_department'] = $this->Department_model->get_all_department();

				$this->load->model('Sport_info_model');
				$data['all_sport_info'] = $this->Sport_info_model->get_all_sport_info();
				$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();
				$data['all_student_registartion'] = $this->Student_registartion_model->get_all_student_registartion();

                $data['_view'] = 'participate_team/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The participate_team you are trying to edit does not exist.');
    } 

    /*
     * Deleting participate_team
     */
    function remove($team_id)
    {
        $participate_team = $this->Participate_team_model->get_participate_team($team_id);

        // check if the participate_team exists before trying to delete it
        if(isset($participate_team['team_id']))
        {
            $this->Participate_team_model->delete_participate_team($team_id);
            redirect('participate_team/index');
        }
        else
            show_error('The participate_team you are trying to delete does not exist.');
    }
    
}
