<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Admin_registration_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    public function login($username, $password)
    {
        
        $query=$this->db->query("select * from admin_registration where email_id='".$username."' and password='".$password."'  ");
        
        if($query->num_rows() > 0)
        {
            foreach ($query->result() as $row)
            {
                $admin_id = $row->id;
                $username = $row->email_id;
            }
            $this->session->set_userdata('admin_id', $admin_id);
            $this->session->set_userdata('username', $username);
            return $query->result();
        }
        else
        {
            return $query->result();
        }
    }
    
    /*
     * Get admin_registration by id
     */
    function get_admin_registration($id)
    {
        return $this->db->get_where('admin_registration',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all admin_registration
     */
    function get_all_admin_registration()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('admin_registration')->result_array();
    }
        
    /*
     * function to add new admin_registration
     */
    function add_admin_registration($params)
    {
        $this->db->insert('admin_registration',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update admin_registration
     */
    function update_admin_registration($admin_id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('admin_registration',$params);
    }
    
    /*
     * function to delete admin_registration
     */
    function delete_admin_registration($id)
    {
        return $this->db->delete('admin_registration',array('id'=>$id));
    }
}
