<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Department_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get department by department_id
     */
    function get_department($department_id)
    {
        return $this->db->get_where('department',array('department_id'=>$department_id))->row_array();
    }
        
    /*
     * Get all department
     */
    function get_all_department()
    {
        $this->db->order_by('department_id', 'desc');
        return $this->db->get('department')->result_array();
    }
        
    /*
     * function to add new department
     */
    function add_department($params)
    {
        $this->db->insert('department',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update department
     */
    function update_department($department_id,$params)
    {
        $this->db->where('department_id',$department_id);
        return $this->db->update('department',$params);
    }
    
    /*
     * function to delete department
     */
    function delete_department($department_id)
    {
        return $this->db->delete('department',array('department_id'=>$department_id));
    }
}
