<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Participate_team_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get participate_team by team_id
     */
    function get_participate_team($team_id)
    {
        return $this->db->get_where('participate_team',array('team_id'=>$team_id))->row_array();
    }
        
    /*
     * Get all participate_team
     */
    function get_all_participate_team()
    {
        /*$this->db->order_by('team_id', 'desc');
        return $this->db->get('participate_team')->result_array();*/
        $query=$this->db->query("select participate_team.*,sport_info.game_name,department.department_name,student_registartion.name from participate_team 
                             LEFT JOIN sport_info ON participate_team.sport = sport_info.id
                             LEFT JOIN department ON participate_team.department = department.department_id 
                             LEFT JOIN student_registartion ON participate_team.leader_registration_id = student_registartion.id
                             
                             
            order by team_id DESC ");
        return $query->result_array();

        
    }
        
    /*
     * function to add new participate_team
     */
    function add_participate_team($params)
    {
        $this->db->insert('participate_team',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update participate_team
     */
    function update_participate_team($team_id,$params)
    {
        $this->db->where('team_id',$team_id);
        return $this->db->update('participate_team',$params);
    }
    
    /*
     * function to delete participate_team
     */
    function delete_participate_team($team_id)
    {
        return $this->db->delete('participate_team',array('team_id'=>$team_id));
    }
}
