<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Participate_individual_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get participate_individual by id
     */
    function get_participate_individual($id)
    {
        return $this->db->get_where('participate_individual',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all participate_individual
     */
    function get_all_participate_individual()
    {
        /*$this->db->order_by('id', 'desc');
        return $this->db->get('participate_individual')->result_array();*/
        $query=$this->db->query("select participate_individual.*,department.department_name from participate_individual LEFT JOIN department ON participate_individual.department = department.department_id order by id DESC ");
        return $query->result_array();
        
    }
        
    /*
     * function to add new participate_individual
     */
    function add_participate_individual($params)
    {
        $this->db->insert('participate_individual',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update participate_individual
     */
    function update_participate_individual($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('participate_individual',$params);
    }
    
    /*
     * function to delete participate_individual
     */
    function delete_participate_individual($id)
    {
        return $this->db->delete('participate_individual',array('id'=>$id));
    }

     function search($id,$key,$params)
    {
        $this->db->like('game_name', $key);
        $query = $this->db->get('participate_individual');
        return $query->result();
    }
}
