<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Sport_info_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get sport_info by id
     */
    function get_sport_info($id)
    {
        return $this->db->get_where('sport_info',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all sport_info
     */
    function get_all_sport_info()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('sport_info')->result_array();
    }
        
    /*
     * function to add new sport_info
     */
    function add_sport_info($params)
    {
        $this->db->insert('sport_info',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update sport_info
     */
    function update_sport_info($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('sport_info',$params);
    }
    
    /*
     * function to delete sport_info
     */
    function delete_sport_info($id)
    {
        return $this->db->delete('sport_info',array('id'=>$id));
    }
}
