<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student_registartion_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function login($username, $password)
    {
        
        $query=$this->db->query("select * from student_registartion where email_id ='".$username."' and password='".$password."'  ");
        echo "select * from student_registartion where email_id ='".$username."' and password='".$password."'";
//exit();

        if($query->num_rows() > 0)
        {
            foreach ($query->result() as $row)
            {
                $student_id = $row->id;
                $student_name = $row->name;
            }
            $this->session->set_userdata('student_id', $student_id);
            $this->session->set_userdata('student_name', $student_name);
            return $query->result();
        }
        else
        {
            return $query->result();
        }
    }   
    
    /*
     * Get student_registartion by id
     */
    function get_student_registartion($id)
    {
        return $this->db->get_where('student_registartion',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all student_registartion
     */
    function get_all_student_registartion()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('student_registartion')->result_array();
    }
        
    /*
     * function to add new student_registartion
     */
    function add_student_registartion($params)
    {
        $this->db->insert('student_registartion',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update student_registartion
     */
    function update_student_registartion($student_id,$params)
    {
        $this->db->where('id',$student_id);
        return $this->db->update('student_registartion',$params);
    }
    
    /*
     * function to delete student_registartion
     */
    function delete_student_registartion($id)
    {
        return $this->db->delete('student_registartion',array('id'=>$id));
    }

   
}
